import React, { useState } from 'react'
import { ChevronDown, ChevronUp } from 'lucide-react'

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div className="border-b border-gray-700 last:border-b-0">
      <button
        className="flex justify-between items-center w-full py-4 text-left focus:outline-none"
        onClick={() => setIsOpen(!isOpen)}
      >
        <h3 className="text-lg font-medium text-white">{question}</h3>
        <span>
          {isOpen ? (
            <ChevronUp className="h-5 w-5 text-purple-400" />
          ) : (
            <ChevronDown className="h-5 w-5 text-purple-400" />
          )}
        </span>
      </button>
      
      {isOpen && (
        <div className="pb-4 text-gray-300">
          <p>{answer}</p>
        </div>
      )}
    </div>
  )
}

const FAQ = () => {
  const faqs = [
    {
      question: "What is xBesh AI?",
      answer: "xBesh AI is an advanced artificial intelligence tool designed specifically for software development. It helps developers write code, debug issues, design interfaces, and solve complex programming challenges with unprecedented speed and accuracy."
    },
    {
      question: "How does xBesh AI compare to other AI coding assistants?",
      answer: "xBesh AI is built specifically for developers with a focus on production-ready code. Unlike general-purpose AI tools, xBesh understands software architecture, best practices, and can generate complete, working applications - not just code snippets."
    },
    {
      question: "Do I need to be online to use xBesh AI?",
      answer: "Yes, xBesh AI requires an internet connection to function as it leverages our powerful cloud-based AI models. This ensures you always have access to the latest capabilities without requiring powerful local hardware."
    },
    {
      question: "What programming languages does xBesh AI support?",
      answer: "xBesh AI supports all major programming languages including JavaScript, TypeScript, Python, Java, C#, PHP, Ruby, Go, Swift, and many more. It also understands popular frameworks like React, Angular, Vue, Node.js, Django, Flask, and others."
    },
    {
      question: "Can I use the code generated by xBesh AI in commercial projects?",
      answer: "Absolutely! All code generated by xBesh AI is yours to use in any project, including commercial applications. There are no licensing restrictions on the output."
    },
    {
      question: "What happens after the launch on May 8th?",
      answer: "After the launch, xBesh AI will be available at its regular pricing. By pre-ordering now, you lock in the special launch discount and will be among the first to access the platform when it goes live."
    },
    {
      question: "Is there a refund policy?",
      answer: "Yes, we offer a 30-day money-back guarantee. If you're not satisfied with xBesh AI for any reason, simply contact our support team within 30 days of purchase for a full refund."
    }
  ]

  return (
    <section id="faq" className="py-16 md:py-24 relative">
      <div className="absolute bottom-0 right-0 w-1/4 h-1/4 bg-purple-600/10 rounded-full filter blur-3xl"></div>
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Frequently Asked Questions</h2>
          <p className="text-xl text-gray-300">
            Everything you need to know about xBesh AI.
          </p>
        </div>
        
        <div className="bg-gray-800/80 border border-purple-500/20 rounded-xl overflow-hidden">
          <div className="divide-y divide-gray-700">
            {faqs.map((faq, index) => (
              <FAQItem 
                key={index}
                question={faq.question}
                answer={faq.answer}
              />
            ))}
          </div>
        </div>
        
        <div className="mt-12 text-center">
          <p className="text-gray-300 mb-4">Still have questions?</p>
          <button className="px-6 py-3 bg-gray-700 hover:bg-gray-600 text-white rounded-lg font-medium transition-all">
            Contact Support
          </button>
        </div>
      </div>
    </section>
  )
}

export default FAQ
